# .github/workflows/web-build.yml
name: Memos Web Build

on:
  push:
    branches: [ "main" ]
    paths: 
      - 'web/**'
      - '.github/workflows/web-build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      NODE_VERSION: '20'
      WORKING_DIRECTORY: 'web'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'

    - name: Install dependencies
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        yarn install --pure-lockfile --network-timeout 300000
        yarn cache list

    - name: Build production assets
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        yarn build
        ls -lh dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: memos-web-build
        path: ${{ env.WORKING_DIRECTORY }}/dist/
        retention-days: 5
        if-no-files-found: error
