name: Web Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 新增：自动生成lockfile的保险措施
    - name: Ensure lockfile exists
      working-directory: web
      run: |
        if [ ! -f "yarn.lock" ]; then
          echo "::warning::Generating yarn.lock..."
          yarn install
        fi

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'
        cache-dependency-path: 'web/yarn.lock'

    - name: Install & Build
      working-directory: web
      run: |
        yarn install --immutable
        yarn build
