# 创建文件路径: .github/workflows/web-build.yml
name: Build Web Assets

on:
  push:
    branches: 
      - main
    paths:
      - 'web/**'
      - '.github/workflows/web-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      working-directory: web
      run: npm install -g yarn && yarn install
    
    - name: Build production assets
      working-directory: web
      run: yarn build
    
    - name: Archive production build
      uses: actions/upload-artifact@v3
      with:
        name: web-build
        path: web/dist/
        retention-days: 5
